<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Tarik" failures="0" tests="8" name="com.chargeSavvy.SearchMerchantTest" time="32.286" errors="2" timestamp="2024-07-01T15:15:39 IST" skipped="6">
  <testcase classname="com.chargeSavvy.SearchMerchantTest" name="verifyAllErrMsgWhenAllFieldareEmpty" time="4.005">
    <skipped/>
  </testcase> <!-- verifyAllErrMsgWhenAllFieldareEmpty -->
  <system-out/>
  <testcase classname="com.chargeSavvy.SearchMerchantTest" name="verifySomethingWentWrongErrMsgWhenRingNumberFieldIsEmpty" time="4.014">
    <skipped/>
  </testcase> <!-- verifySomethingWentWrongErrMsgWhenRingNumberFieldIsEmpty -->
  <system-out/>
  <testcase classname="com.chargeSavvy.SearchMerchantTest" name="verifyAllErrMsgWhenAllFieldareEmpty" time="4.010">
    <error message="Cannot invoke &quot;com.chargeSavvy.SavvyLoginPage.LOGIN()&quot; because &quot;this.login&quot; is null" type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "com.chargeSavvy.SavvyLoginPage.LOGIN()" because "this.login" is null
at com.chargeSavvy.SearchMerchantTest.verifyAllErrMsgWhenAllFieldareEmpty(SearchMerchantTest.java:139)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
]]>
    </error>
  </testcase> <!-- verifyAllErrMsgWhenAllFieldareEmpty -->
  <system-out/>
  <testcase classname="com.chargeSavvy.SearchMerchantTest" name="verifyAllErrMsgWhenAllFieldareEmpty" time="4.015">
    <skipped/>
  </testcase> <!-- verifyAllErrMsgWhenAllFieldareEmpty -->
  <system-out/>
  <testcase classname="com.chargeSavvy.SearchMerchantTest" name="verifySomethingWentWrongErrMsgWhenRingNumberFieldIsEmpty" time="4.008">
    <skipped/>
  </testcase> <!-- verifySomethingWentWrongErrMsgWhenRingNumberFieldIsEmpty -->
  <system-out/>
  <testcase classname="com.chargeSavvy.SearchMerchantTest" name="verifySomethingWentWrongErrMsgWhenRingNumberFieldIsEmpty" time="4.011">
    <error message="Cannot invoke &quot;com.chargeSavvy.SavvyLoginPage.LOGIN()&quot; because &quot;this.login&quot; is null" type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "com.chargeSavvy.SavvyLoginPage.LOGIN()" because "this.login" is null
at com.chargeSavvy.SearchMerchantTest.verifySomethingWentWrongErrMsgWhenRingNumberFieldIsEmpty(SearchMerchantTest.java:118)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
]]>
    </error>
  </testcase> <!-- verifySomethingWentWrongErrMsgWhenRingNumberFieldIsEmpty -->
  <system-out/>
  <testcase classname="com.chargeSavvy.SearchMerchantTest" name="verifyAllErrMsgWhenAllFieldareEmpty" time="4.213">
    <skipped/>
  </testcase> <!-- verifyAllErrMsgWhenAllFieldareEmpty -->
  <system-out/>
  <testcase classname="com.chargeSavvy.SearchMerchantTest" name="verifySomethingWentWrongErrMsgWhenRingNumberFieldIsEmpty" time="4.010">
    <skipped/>
  </testcase> <!-- verifySomethingWentWrongErrMsgWhenRingNumberFieldIsEmpty -->
  <system-out/>
</testsuite> <!-- com.chargeSavvy.SearchMerchantTest -->
